customfunction remove "form_bootstrap/main"
customfunction remove "form_bootstrap/v1"
customfunction remove "form_bootstrap/v1.1"
customfunction remove "form_bootstrap/v1.2"
customfunction remove "form_bootstrap/v1.3"